name: Python CI

on:
  push:
    branches: [main, develop, etl]
  pull_request:
    branches: [main, develop, etl]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.11']   

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Step 1: Cache dependencies for faster builds
      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 2: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff # Install linter separately

      # Step 3: Run Linter for code quality
      - name: Run linter
        run: ruff check .

      # Step 4: Run tests and generate coverage report
      - name: Run tests with coverage
        run: |
          export TEST_ENV=true
          PYTHONPATH=src pytest --cov=src --cov-report=xml tests/

      # Step 5: Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
